# Generated by Django 6.0.5 on 2026-05-20 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=180)),
                ('ciudad', models.CharField(default='Bogota', max_length=80)),
                ('capacidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['ciudad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='publicado', max_length=20)),
                ('imagen_url', models.URLField(blank=True, verbose_name='URL de imagen')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.categoria')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.ubicacion')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cupo', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_entrada', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'tipo de entrada',
                'verbose_name_plural': 'tipos de entrada',
                'ordering': ['evento', 'precio'],
                'unique_together': {('evento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('referencia_pago', models.CharField(blank=True, max_length=80)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='eventos.evento')),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='eventos.tipoentrada')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_imagen', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('usada', 'Usada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='eventos.evento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='eventos.orden')),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='eventos.tipoentrada')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ingresado', models.CharField(max_length=80)),
                ('resultado', models.CharField(choices=[('valida', 'Valida'), ('invalida', 'Invalida')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=180)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to='eventos.entrada')),
                ('validado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validacion de acceso',
                'verbose_name_plural': 'validaciones de acceso',
                'ordering': ['-creado'],
            },
        ),
    ]
